ionic-team/capacitor-plugins

- scripts/toggle-local.mjs
This kept being set back to 'next'
> replaced next with latest alpha version

- haptics/LICENSE
- motion/LICENSE
- screen-reader/LICENSE
- storage/LICENSE
- text-zoom/LICENSE
resolves https://github.com/ionic-team/capacitor-plugins/issues/28
> chore: add LICENSE file to each plugin

- haptics/README.md
- motion/README.md
- screen-reader/README.md
- screen-reader/package.json
- storage/README.md
- storage/package.json
- text-zoom/README.md
- text-zoom/package.json
resolves https://github.com/ionic-team/capacitor-plugins/issues/29
> chore: add README.md file to each plugin

- clipboard/package.json
- clipboard/src/index.ts
- clipboard/src/web.ts
- haptics/package.json
- haptics/src/index.ts
- haptics/src/web.ts
- motion/package.json
- motion/src/definitions.ts
- motion/src/index.ts
- motion/src/web.ts
- network/ios/Plugin/Network.swift
- network/package.json
- network/src/definitions.ts
- network/src/index.ts
- network/src/web.ts
- screen-reader/package.json
- screen-reader/src/definitions.ts
- screen-reader/src/index.ts
- screen-reader/src/web.ts
- storage/package.json
- storage/src/index.ts
- storage/src/web.ts
- text-zoom/package.json
- text-zoom/src/index.ts
- text-zoom/src/ios.ts
Following suit from https://github.com/ionic-team/capacitor/pull/3539
> chore: integrate ESLint

- browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
The plugin doesn't use the request code
> chore(browser): remove unused request code

- share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
Update for upcoming Capacitor 3 alpha 7 build
> refactor(android): updated share plugin handleOnActivityResult signature

- action-sheet/src/definitions.ts
- app-launcher/src/definitions.ts
- app/src/definitions.ts
- browser/src/definitions.ts
- clipboard/src/definitions.ts
- device/src/definitions.ts
- dialog/src/definitions.ts
- haptics/src/definitions.ts
- keyboard/src/definitions.ts
- motion/src/definitions.ts
- network/src/definitions.ts
- screen-reader/src/definitions.ts
- share/src/definitions.ts
- status-bar/src/definitions.ts
- storage/src/definitions.ts
- text-zoom/src/definitions.ts
- toast/src/definitions.ts
see https://github.com/ionic-team/create-capacitor-plugin/pull/33
> chore: remove plugin registry types

- app-launcher/src/web.ts
Make openUrl to actually open the url with `window.open`
> feat(app-launcher): make openUrl open urls

- action-sheet/android/build.gradle
- app-launcher/android/build.gradle
- app/android/build.gradle
- browser/android/build.gradle
- camera/android/build.gradle
- clipboard/android/build.gradle
- device/android/build.gradle
- dialog/android/build.gradle
- filesystem/android/build.gradle
- geolocation/android/build.gradle
- haptics/android/build.gradle
- keyboard/android/build.gradle
- network/android/build.gradle
- screen-reader/android/build.gradle
- share/android/build.gradle
- splash-screen/android/build.gradle
- status-bar/android/build.gradle
- storage/android/build.gradle
- text-zoom/android/build.gradle
- toast/android/build.gradle
> style: fix spacing in build.gradle dependency versions

- push-notifications/CapacitorPushNotifications.podspec
fixes https://github.com/ionic-team/capacitor-plugins/issues/182
> fix(push-notifications): bump iOS deployment target to 12.0

- local-notifications/src/web.ts
this lines were removed on the migration and makes the schedule now to not work
https://github.com/ionic-team/capacitor/blob/2.x/core/src/web/local-notifications.ts#L55-L68
> fix(web): fix scheduled notifications not being sent

- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java
- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java
- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/TimedNotificationPublisher.java
closes https://github.com/ionic-team/capacitor-plugins/issues/216
> fix(local-notifications): fire localNotificationReceived event on Android

- filesystem/ios/Plugin/FilesystemPlugin.swift
> fix(filesystem): rmdir doesn't resolve on iOS

- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
> fix(filesystem): copy doesn't resolve on Android

- local-notifications/src/web.ts
> fix(local-notifications): implement ActionPerformed and Received events

- app/README.md
closes https://github.com/ionic-team/capacitor-plugins/issues/108
> docs(app): Add information about how to register custom schemes

- local-notifications/README.md
- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/DateMatch.java
- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationSchedule.java
- local-notifications/src/definitions.ts
This PR adds the ability to define seconds on the `on` property of `LocalNotificationSchedule`.
fixes: https://github.com/ionic-team/capacitor/issues/1679
> feat(local-notifications): Support setting seconds in Schedule "on"

- camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
- geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java
- network/android/src/main/java/com/capacitorjs/plugins/network/NetworkPlugin.java
Changes related to permission API cleanup https://github.com/ionic-team/capacitor/pull/4171
> refactor(android): permission API cleanup changes

- action-sheet/README.md
- action-sheet/android/build.gradle
- camera/README.md
- camera/android/build.gradle
use the final instead of the RC
> chore: Update androidxMaterialVersion

- storage/android/src/main/java/com/capacitorjs/plugins/storage/StoragePlugin.java
- storage/ios/Plugin/StoragePlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/255
> fix(storage): configure doesn't resolve on Android and iOS

- filesystem/ios/Plugin.xcworkspace/contents.xcworkspacedata
The file was created after verify and all other plugins have it, so adding it for filesystem too.
> chore(filesystem): Add missing file

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- push-notifications/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- storage/package.json
- text-zoom/package.json
- toast/package.json
Mostly to test if CI is still broken.
> chore: update typescript to ~4.1

- filesystem/README.md
closes https://github.com/ionic-team/capacitor-plugins/issues/281
> docs(filesystem): update example with proper import

- app/README.md
- app/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/289
> fix(app): Update getLaunchUrl return type as can be undefined

- .gitignore
- filesystem/ios/Plugin/FilesystemPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/303
> fix(filesystem): Append doesn't resolve on iOS

- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/NotificationStorage.java
closes https://github.com/ionic-team/capacitor-plugins/issues/309
> fix(local-notifications): don't store notifications if not scheduled

- browser/ios/Plugin/BrowserPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/352
> fix(browser): prevent crash on popover presentation

- geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/364
> fix(geolocation): Replace deprecated call.save with new keepAlive API

- geolocation/ios/Plugin/GeolocationPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/362
> fix(geolocation): Use the new APIs for handling/saving calls

- camera/src/web.ts
- clipboard/src/index.ts
- device/src/__tests__/useragent.spec.ts
- haptics/src/web.ts
- local-notifications/src/web.ts
- package.json
not sure what happened, we were already using latest prettier and lint failed again and fmt proposes this changes
> chore: run fmt again

- filesystem/README.md
- filesystem/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/203
> docs(filesystem): Document permissions and quirks

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- haptics/package.json
- keyboard/README.md
- keyboard/package.json
- local-notifications/README.md
- local-notifications/package.json
- motion/package.json
- network/package.json
- push-notifications/README.md
- push-notifications/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/README.md
- splash-screen/package.json
- status-bar/package.json
- storage/package.json
- text-zoom/package.json
- toast/package.json
requires @capacitor/docgen 0.0.17 update
> docs: Use export in module style

- status-bar/ios/Plugin/StatusBarPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/357
> chore(status-bar): Remove observer on deinit

- push-notifications/ios/Plugin/PushNotificationsPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/358
> chore(push-notifications): Remove observer on deinit

- app/ios/Plugin/AppPlugin.swift
release block based observers on deinit
closes https://github.com/ionic-team/capacitor-plugins/issues/356
> chore(app): Remove observers on deinit

- push-notifications/README.md
- push-notifications/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/pull/429
> docs(push-notifications): register doesn't prompt

- storage/README.md
> chore(storage): fix typo in readme

- browser/README.md
- browser/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/559
> docs(browser): Add clarifications to browser events

- keyboard/README.md
- keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java
- keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/KeyboardPlugin.java
- keyboard/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/626
> feat(Keyboard): Add resizeOnFullScreen plugin configuration

- keyboard/ios/Plugin/Keyboard.m
closes https://github.com/ionic-team/capacitor-plugins/issues/621
> feat(keyboard): Make resize work in apps that use scenes

- push-notifications/README.md
closes https://github.com/ionic-team/capacitor-plugins/issues/647
> docs(push-notifications): Add Example section in README

- haptics/README.md
- haptics/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/pull/753
> docs(haptics): Update heavy description to match Apple docs

- splash-screen/ios/Plugin/SplashScreen.swift
> fix(splash-screen): avoid conditional downcast warning

- keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java
closes https://github.com/ionic-team/capacitor-plugins/issues/787
> fix(keyboard): Prevent null pointer if native listener not set

- google-maps/CapacitorGoogleMaps.podspec
- google-maps/ios/Plugin.xcodeproj/project.pbxproj
- google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift
- google-maps/ios/Podfile
implements: https://ionic-cloud.atlassian.net/browse/WN-230
> feat: Add iOS Google Maps SDK

- push-notifications/README.md
- push-notifications/android/build.gradle
closes https://github.com/ionic-team/capacitor-plugins/issues/394
> chore(push-notifications): Update firebase dependencies

- google-maps/README.md
- google-maps/e2e-tests/src/pages/Map/CreateAndDestroyMap.tsx
- google-maps/e2e-tests/src/pages/Markers/AddAndRemoveMarkers.tsx
- google-maps/e2e-tests/src/pages/Markers/MultipleMarkers.tsx
- google-maps/package.json
- google-maps/rollup.config.js
- google-maps/src/definitions.ts
- google-maps/src/implementation.ts
- google-maps/src/map.ts
- google-maps/src/web.ts
This PR adds dynamic loading of the web based google maps SDK and basic api support on the plugin for web.
> feat: dynamic web google maps

- geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java
closes https://github.com/ionic-team/capacitor-plugins/issues/790
> refactor(geolocation): Replace deprecated LocationRequest constructor

- toast/README.md
- toast/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/688
> docs(toast): Document that position doesn't work on Android 12

- browser/android/src/main/java/com/capacitorjs/plugins/browser/Browser.java
closes https://github.com/ionic-team/capacitor-plugins/issues/839
> refactor(browser): Replace deprecated code with alternatives

- action-sheet/android/build.gradle
- app-launcher/android/build.gradle
- app/android/build.gradle
- browser/android/build.gradle
- camera/android/build.gradle
- clipboard/android/build.gradle
- device/android/build.gradle
- dialog/android/build.gradle
- filesystem/android/build.gradle
- geolocation/android/build.gradle
- haptics/android/build.gradle
- keyboard/android/build.gradle
- local-notifications/android/build.gradle
- network/android/build.gradle
- push-notifications/android/build.gradle
- screen-reader/android/build.gradle
- share/android/build.gradle
- splash-screen/android/build.gradle
- status-bar/android/build.gradle
- storage/android/build.gradle
- text-zoom/android/build.gradle
- toast/android/build.gradle
> chore: min sdk bumps for each plugin

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- push-notifications/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- storage/package.json
- text-zoom/package.json
- toast/package.json
Use next tag for capacitor dependencies until it's final
> chore: Update Capacitor dependencies to next

- network/android/src/main/java/com/capacitorjs/plugins/network/Network.java
- share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
> chore: remove all unused conditional code from plugins

- local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java
closes https://github.com/ionic-team/capacitor-plugins/issues/689
> fix(local-notifications): Add FLAG_MUTABLE to pending intents for SDK 31

- google-maps/e2e-tests/src/pages/Scrolling/SimpleScrolling.tsx
- google-maps/e2e-tests/src/theme/variables.css
- google-maps/package.json
- google-maps/src/implementation.ts
- google-maps/src/map.ts
- google-maps/src/web.ts
This PR fixes the scroll listeners for ionic apps and allows for inline scrolling on Android.
> fix(android): scroll detection for ionic apps

- filesystem/README.md
- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java
- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
- filesystem/ios/Plugin/FilesystemPlugin.swift
- filesystem/src/definitions.ts
- filesystem/src/web.ts
Make readDir return an array of objects with information about the files listed, similar to the information StatResult returns
closes https://github.com/ionic-team/capacitor-plugins/issues/900
> feat(filesystem): Make readDir return files information

- google-maps/README.md
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
- google-maps/ios/Plugin/Map.swift
- google-maps/src/implementation.ts
- google-maps/src/map.ts
- google-maps/src/web.ts
This PR ignores map touch events if the map is not the top most layer.
closes: https://ionic-cloud.atlassian.net/browse/WN-436
closes: https://github.com/ionic-team/capacitor-plugins/issues/953
> fix(google-maps): Fixing map touch events overriding html elements on Android

- google-maps/README.md
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/GoogleMapConfig.kt
- google-maps/src/definitions.ts
- google-maps/src/implementation.ts
- google-maps/src/map.ts
This PR adds typing and documentation for the event listeners on google maps.
> fix(google-maps): correctly typed event listeners

- camera/ios/Plugin/CameraExtensions.swift
requestImageData was renamed to requestImageDataAndOrientation
> chore(camera): remove deprecation warning

- local-notifications/README.md
- local-notifications/src/definitions.ts
- push-notifications/README.md
- push-notifications/src/definitions.ts
for both local-notifications and push-notifications
closes https://github.com/ionic-team/capacitor-plugins/issues/453
> chore: change deleteChannel to accept only the channel id

- network/CapacitorNetwork.podspec
- network/ios/Plugin.xcodeproj/project.pbxproj
- network/ios/Plugin/Network.swift
- network/ios/Plugin/Reachability.swift
- network/ios/Podfile
Addresses: [WN-351](https://ionic-cloud.atlassian.net/browse/WN-351)
Brings the external dependancy into the project as source. The project was MIT licensed and the copyright is maintained in the source.
> chore(network): remove Reachability.swift dependency integrating source code

- google-maps/CapacitorGoogleMaps.podspec
I committed this changes to native-publish branch while trying to publish to CocoaPods as it was different from other plugins and was causing issues.
> chore(google-maps): align podspec with other plugins

- camera/README.md
- camera/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/pull/1086
> docs(camera): fix typo in description

- README.md
closes https://github.com/ionic-team/capacitor-plugins/issues/1087
> chore: Update README with v4 links

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- google-maps/e2e-tests/package.json
- google-maps/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- preferences/package.json
- push-notifications/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- text-zoom/package.json
- toast/package.json
Use ^4.0.0 instead of next as next is the beta
> chore: Update devDependencies and peerDependencies to 4

- google-maps/src/map.ts
The platform is being logged for all apps using google-maps plugin.
> chore(google-maps): Remove platform log

- filesystem/ios/Plugin/Filesystem.swift
- filesystem/ios/Plugin/FilesystemPlugin.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/1131
> fix(filesystem): make iOS return proper url on readdir

- camera/README.md
- camera/src/definitions.ts
Filesystem API typo errors on the same file
> docs(camera): Fix Filsystem typos

- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
Addresses: https://github.com/ionic-team/capacitor-plugins/issues/1176
This PR fixes an issue on Android where event listeners such as `onCameraIdle`, `onBoundsChanged`, and `onMarkerClick` were not being triggered when clustering is enabled.
> fix(google-maps): event listeners not firing when clustering enabled

- share/README.md
- share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
- share/ios/Plugin/SharePlugin.swift
- share/src/definitions.ts
add a new files property on share method that allows to provide multiple file paths to be shared.
> feat(share): Support for sharing multiple files

- google-maps/README.md
- google-maps/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/1218
> docs(google-maps): Document unused animationDuration

- browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/1283
> fix(browser): Reject if custom tabs are not available

- splash-screen/README.md
closes https://github.com/ionic-team/capacitor/issues/6190
> docs(splash-screen): Add more information about Android 12 bugs

- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
This PR addresses #1309 and re-clusters when the map moves, zooms, or rotates.
> fix(google-maps/android): update clusters on map move

- google-maps/README.md
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
- google-maps/e2e-tests/ios/App/App.xcodeproj/project.pbxproj
- google-maps/e2e-tests/src/pages/Markers/MultipleMarkers.tsx
- google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift
- google-maps/ios/Plugin/Map.swift
- google-maps/src/implementation.ts
- google-maps/src/map.ts
- google-maps/src/web.ts
This PR allows modification of the minimum cluster size so behavior can be matched across all platforms. (Default minClusterSize is 4 on the Android & iOS SDKs)
> feat(google-maps): Add minClusterSize setting for enableClustering

- splash-screen/README.md
- splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java
- splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java
- splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java
- splash-screen/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/1322
> feat(splash-screen): Add launchFadeOutDuration configuration option

- screen-orientation/ios/Plugin/ScreenOrientation.swift
remove code that was there for Xcode 13 support
> chore(screen-orientation): Drop Xcode 13 support

- push-notifications/README.md
- push-notifications/android/src/main/AndroidManifest.xml
- push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java
- push-notifications/src/definitions.ts
Implements support for notifications permissions in Android 13 (API 33):
https://developer.android.com/develop/ui/views/notifications/notification-permission
> feat(push-notifications): support Android 13+ permissions

- google-maps/e2e-tests/android/build.gradle
- google-maps/e2e-tests/android/gradle/wrapper/gradle-wrapper.properties
- google-maps/e2e-tests/android/variables.gradle
Update Android dependencies for the `google-maps` test app.
> chore(google-maps): update testapp deps

- screen-orientation/android/src/main/java/com/capacitorjs/plugins/screenorientation/ScreenOrientation.java
- screen-orientation/ios/Plugin/ScreenOrientation.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/1452
> fix(screen-orientation): Add native implementation for landscape and any

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- google-maps/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- preferences/package.json
- push-notifications/package.json
- screen-orientation/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- text-zoom/package.json
- toast/package.json
Closes https://github.com/ionic-team/capacitor-plugins/issues/1575
> fix: Use Capacitor 5 final

- google-maps/README.md
- google-maps/e2e-tests/src/pages/Map/Localization.tsx
- google-maps/e2e-tests/src/routes.ts
- google-maps/src/implementation.ts
- google-maps/src/web.ts
Adds the ability to set the language and region for web-based Google Maps.
closes: https://github.com/ionic-team/capacitor-plugins/issues/957
> feat(google-maps):  Add ability to set language and region on map

- keyboard/README.md
- keyboard/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/1150
> docs(keyboard): document keyboard events limitation

- share/README.md
closes https://github.com/ionic-team/capacitor-plugins/issues/194
> docs(share): Add sharing files examples

- keyboard/ios/Plugin/Keyboard.m
This PR fixes a regression introduced in 4.1.1, while maintaining compatibility with Stage Manager.
closes: https://github.com/ionic-team/capacitor-plugins/issues/1413
> fix(keyboard): fixing webview resizing when keyboard visible

- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapMarker.kt
- google-maps/src/web.ts
Closes https://github.com/ionic-team/capacitor-plugins/issues/1644
> fix(google-maps): Apply zIndex for marker in Android and default to 0

- push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/1628
> fix(push-notifications): make requestPermissions resolve if granted

- filesystem/README.md
- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java
- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
- filesystem/ios/Plugin/Filesystem.swift
- filesystem/ios/Plugin/FilesystemPlugin.m
- filesystem/ios/Plugin/FilesystemPlugin.swift
- filesystem/package.json
- filesystem/src/definitions.ts
- filesystem/src/web.ts
- package.json
This PR adds `downloadFile` support for the `filesystem` plugin.
Needs Core Change before Merging: https://github.com/ionic-team/capacitor/pull/6657
Test App PR: https://github.com/ionic-team/capacitor-testapp/pull/591
> feat(filesystem): download files from server to filesystem

- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
- google-maps/e2e-tests/src/pages/Map/ResizeMap.tsx
- google-maps/e2e-tests/src/routes.ts
- google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.m
- google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift
- google-maps/ios/Plugin/Map.swift
- google-maps/package.json
- google-maps/src/implementation.ts
- google-maps/src/map.ts
- google-maps/src/web.ts
In this PR I added the feature to update the map size when the html wrapper container changes its size. Its implemented with the help of a ResizeObserver which then calls the native `updateRender` methods.
Closes https://github.com/ionic-team/capacitor-plugins/issues/1594
> feat(google-maps): Update map size in updateRender method if it has changed

- filesystem/README.md
looks like the data was changed to any and then to string | Blob, but was not regenerated after the change
> docs(filesystem): Regenerate README

- browser/android/src/main/AndroidManifest.xml
- browser/android/src/main/java/com/capacitorjs/plugins/browser/Browser.java
closes #76 
Added requested changes.
> feat(browser): support other custom tabs providers

- push-notifications/README.md
- push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/NotificationChannelManager.java
- push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java
Porting https://github.com/ionic-team/capacitor-plugins/pull/1657 to the 5.x branch.
> feat(push-notifications): use Firebase SDK for creating foreground notifications

- filesystem/CHANGELOG.md
- filesystem/package.json
- google-maps/CHANGELOG.md
- google-maps/package.json
- @capacitor/filesystem@5.1.3
- @capacitor/google-maps@5.3.1
> chore(release): publish [skip ci]

- filesystem/README.md
- filesystem/ios/Plugin/FilesystemPlugin.m
- filesystem/src/definitions.ts
This PR adds the missing method `removeAllListeners`.
> feat(filesystem): add `removeAllListeners` method

- scripts/lib/lerna.mjs
- scripts/set-capacitor-version.mjs
- scripts/update-all.mjs
like https://github.com/ionic-team/capacitor-plugins/pull/1847 but for all other scripts using lerna's bootstrap command that is no longer available
> chore: Remove lerna bootstrap form scripts

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- filesystem/package.json
- geolocation/package.json
- google-maps/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- preferences/package.json
- push-notifications/package.json
- screen-orientation/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- text-zoom/package.json
- toast/package.json
similar to core capacitor, Lerna has issues with major bump.
> chore: bump version to 6.0.0-alpha.0

- keyboard/package.json
keyboard plugin 6.0.0 alpha 0 is empty, add the files to the package.json
> fix(keyboard): distribute the new SPM files

- action-sheet/package.json
- app-launcher/package.json
- app/package.json
- browser/package.json
- camera/package.json
- clipboard/package.json
- device/package.json
- dialog/package.json
- geolocation/package.json
- google-maps/e2e-tests/package.json
- google-maps/package.json
- haptics/package.json
- keyboard/package.json
- local-notifications/package.json
- motion/package.json
- network/package.json
- preferences/package.json
- push-notifications/package.json
- screen-orientation/package.json
- screen-reader/package.json
- share/package.json
- splash-screen/package.json
- status-bar/package.json
- text-zoom/package.json
- toast/package.json
We updated the dev dependencies, but missed the peer dependencies.
> chore: Update core peer dependency to next

- keyboard/ios/Sources/KeyboardPlugin/Keyboard.m
Fixes an issue on iOS 17 where setting keyboard style would not apply the new appearance.
closes: https://github.com/ionic-team/capacitor-plugins/issues/1905
> fix(keyboard): Change keyboard style during setStyle

- google-maps/README.md
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
- google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/GoogleMapConfig.kt
- google-maps/ios/Plugin/GoogleMapConfig.swift
- google-maps/ios/Plugin/Map.swift
- google-maps/src/definitions.ts
- google-maps/src/web.ts
cherry-pick https://github.com/ionic-team/capacitor-plugins/pull/1750
> feat(google-maps): Separate mapId for Google Maps Cloud IDs

- camera/src/web.ts
cherry-pick https://github.com/ionic-team/capacitor-plugins/pull/1958
> fix(camera): reject promise on web input cancel event 

- filesystem/package.json
filesystem plugin didn't have the dependencies/peer dependencies set to use next and beta fails to install
> fix(filesystem): use next tag for capacitor dependencies

- share/android/build.gradle
- status-bar/android/build.gradle
we have updated in the template, but not in the plugins
> chore(android): Update default value of androidxCoreVersion

- filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
cherry pick https://github.com/ionic-team/capacitor-plugins/pull/1990
> fix(filesystem): requestPermissions not resolving 

- app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/1955
> refactor(app)!: use moveTaskToBack within minimizeApp

- .github/workflows/ci.yml
- .github/workflows/publish-ios.yml
- .github/workflows/publish-npm-alpha.yml
- .github/workflows/publish-npm-beta.yml
- .github/workflows/publish-npm-dev.yml
- .github/workflows/publish-npm-latest-from-pre.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-nightly.yml
- .github/workflows/publish-npm-rc.yml
to speed up tests since they use silicon macs now
> chore(ci): update to macos-14

- camera/ios/Plugin/CameraPlugin.swift
> fix(ios): Picking ProRAW pictures from Gallery (#2098)

- keyboard/ios/Sources/KeyboardPlugin/Keyboard.m
Avoids breaking apps that use Apple CarPlay.
References: https://outsystemsrd.atlassian.net/browse/RMET-3229
> fix(ios): apply filter to fetch correct scene object

- action-sheet/ios/Sources/ActionSheetPlugin/ActionSheetPlugin.swift
- app-launcher/ios/Sources/AppLauncherPlugin/AppLauncherPlugin.swift
- browser/ios/Sources/BrowserPlugin/BrowserPlugin.swift
- camera/ios/Sources/CameraPlugin/CameraPlugin.swift
- network/ios/Sources/NetworkPlugin/NetworkPlugin.swift
- network/ios/Tests/NetworkPluginTests/PluginTests.swift
- preferences/ios/Sources/PreferencesPlugin/PreferencesPlugin.swift
- preferences/ios/Tests/PreferencesPluginTests/PluginTests.swift
- push-notifications/ios/Sources/PushNotificationsPlugin/PushNotificationsPlugin.swift
- push-notifications/ios/Tests/PushNotificationsPluginTests/PushNotificationsPluginTests.swift
- screen-orientation/ios/Sources/ScreenOrientationPlugin/ScreenOrientationPlugin.swift
- screen-orientation/ios/Tests/ScreenOrientationPluginTests/ScreenOrientationTests.swift
- screen-reader/ios/Sources/ScreenReaderPlugin/ScreenReaderPlugin.swift
- screen-reader/ios/Tests/ScreenReaderPluginTests/PluginTests.swift
- share/ios/Sources/SharePlugin/SharePlugin.swift
- share/ios/Tests/SharePluginTests/PluginTests.swift
- splash-screen/ios/Sources/SplashScreenPlugin/SplashScreenPlugin.swift
- splash-screen/ios/Tests/SplashScreenPluginTests/SplashScreenPluginTests.swift
- text-zoom/ios/Sources/TextZoomPlugin/TextZoomPlugin.swift
- text-zoom/ios/Tests/TextZoomPluginTests/PluginTests.swift
- toast/ios/Sources/ToastPlugin/ToastPlugin.swift
- toast/ios/Tests/ToastPluginTests/ToastPluginTests.swift
ran `npm run fmt` command to remove whitespaces, commans and unneeded methods on tests
> chore: run fmt command

- .github/workflows/ci.yml
- .github/workflows/publish-npm-latest-from-pre.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-nightly.yml
- lerna.json
Update 6.x branch CI workflows and lerna to use 6.x branch
> chore: update for 6.x branch

- local-notifications/README.md
- push-notifications/README.md
Updates README of relevant plugins with information on Android 15 and Private Space.
> docs: Android 15 - Private Space

- browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
cherry picks [this](https://github.com/ionic-team/capacitor-plugins/pull/2274) fix for cap 6
> fix(browser): crash when trying to open blob urls on android (#2274)
