share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
equivalent of https://github.com/ionic-team/capacitor/pull/3655
=> fix(share): Avoid SecurityError on Android 10 file share

haptics/README.md, haptics/src/definitions.ts, haptics/src/web.ts
This would be a breaking change in Haptics if people were using it, so not merging right away (unlike https://github.com/ionic-team/capacitor/pull/3671)
=> chore(haptics): consistent enum naming style

action-sheet/README.md, app-launcher/README.md, browser/README.md, clipboard/README.md, device/README.md, dialog/README.md, haptics/README.md, keyboard/README.md, motion/README.md, network/README.md, screen-reader/README.md, share/README.md, status-bar/README.md, storage/README.md, text-zoom/README.md, toast/README.md
This is step 1 in documenting these plugins.
Step 2 is adding usage examples.
=> docs: add simple installation instructions

storage/ios/Plugin/StoragePlugin.swift
getString doesn't return optional anymore if it has a default value
=> fix(storage): Remove warning on getString usage

status-bar/ios/Plugin/StatusBarPlugin.swift
Alpha 7 deprecated a few methods that were used in status-bar plugin.
This PR replaces them with the non deprecated alternatives.
=> fix(status-bar): remove deprecate warnings

browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
load should not have `PluginMethod` annotation
=> fix(browser): don't expose load method

camera/android/src/main/AndroidManifest.xml
When targeting SDK 30, users need to add the intents their app launch in their manifest the intents their app launches.
We can document it and make users do it, or we can put the queries on the plugin's `AndroidManifest.xml` for them as manifest merger will put it in the app's `AndroidManifest.xml` manifest too.
I went with the second approach because I think if users installed the plugin they will need this and they can miss it on the docs, so not having to manually add it is a better user experience.
=> fix(camera): query IMAGE_CAPTURE intent required by SDK 30

scripts/toggle-local.mjs
During local plugin development, the npm script `toggle-local` may fail completely if all capacitor projects aren't referenced in a plugin's package devDependencies.
=> chore(scripts): Skip over projects that don't exist in devDependencies

camera/ios/Plugin/CameraPlugin.swift
Capacitor 2 used a file:// URL for the path to the photo (https://github.com/ionic-team/capacitor/blob/2.x/ios/Capacitor/Capacitor/Plugins/Camera.swift#L390). It looks like this was changed during a refactor. This PR returns the `absoluteString` which includes the file protocol to avoid a breaking change in the camera plugin when people update from v2 to v3.
=> fix(camera): return file URL for path, not system path

push-notifications/CapacitorPushNotifications.podspec
It was probably added because of the firebase dependency, but since it was removed, this is no longer needed.
=> chore(push-notifications): Remove s.static_framework = true from podspec

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
The Android permissions were inadvertently split into two aliases during testing and development of permission updates, but this change was not made through the entire plugin across all platforms. This PR changes the Android permissions back to one alias.
=> fix(android): permissions use "publicStorage" as alias

push-notifications/README.md, push-notifications/ios/Plugin.xcodeproj/project.pbxproj
The `FirebaseMessaging.framework` was still in the project and the README said the plugin uses Firebase, which is not true anymore, so removing that part too.
=> chore(push-notifications): Remove Firebase leftovers

push-notifications/ios/Plugin/PushNotificationsHandler.swift
In Capacitor 2, push notifications where not shown when the app was in foreground (by default, but can be configured to show them)
This PR changes the behavior to do the same
closes https://github.com/ionic-team/capacitor-plugins/issues/208
=> fix(ios): do not show notifications when in foreground

push-notifications/src/definitions.ts
Continuation of https://github.com/ionic-team/capacitor-plugins/pull/139, looks like we missed some for Push Notifications.
=> fix: support deprecated types from Capacitor 2

action-sheet/README.md, browser/README.md, camera/README.md, geolocation/README.md, push-notifications/README.md
I'm not sure if we should document ALL the plugin variables in EVERY plugin, or just the unique ones.
=> docs(android): document plugin variables

local-notifications/README.md, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java, local-notifications/ios/Plugin/LocalNotificationsHandler.swift, local-notifications/src/definitions.ts
`localNotificationActionPerformed` was renamed to `actionPerformed` and `localNotificationReceived` to `received`, but old names weren't deprecated, nor fired anymore, nor documented as breaking change, so this PR brings the old names back.
=> fix(local-notifications): Use the old event names

local-notifications/README.md, local-notifications/ios/Plugin/LocalNotificationsHandler.swift, local-notifications/ios/Plugin/LocalNotificationsPlugin.swift
Didn't want to commit to the branch directly, but I think this changes address my requested changes on https://github.com/ionic-team/capacitor-plugins/pull/195#pullrequestreview-576553874
=> add missing ints

local-notifications/README.md, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotification.java, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java, local-notifications/ios/Plugin/LocalNotificationsHandler.swift, local-notifications/ios/Plugin/LocalNotificationsPlugin.swift, local-notifications/src/definitions.ts, local-notifications/src/web.ts
Scheduling a notification takes an integer ID, yet canceling a notification expects a string (and will do nothing if a integer is sent).
This PR brings consistency to the schedule and cancel methods, now requiring an integer ids for both operations.
closes https://github.com/ionic-team/capacitor-plugins/issues/176
=> fix: normalize use of integers for notification IDs

push-notifications/ios/Plugin/PushNotificationsHandler.swift
The cast to `JSObject` makes the push events to miss some data, by using `coerceDictionaryToJSObject` that information is not lost.
closes https://github.com/ionic-team/capacitor-plugins/issues/207
=> fix(push-notifications): Avoid missing push data on events

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
The test app silently fails on copy and rename buttons because it tries to create a file without scheme and that's not supported.
This PR add support for writing files using file urls without a scheme (`file:///whatever` is equivalent to `whatever` but at the moment first one woks and second silently fail). All other file functions support file scheme and no scheme on file urls.
With the PR, you can write files without having the `file` scheme, and also fails if the user uses a scheme that is not supported (that was also silently failing)
related to https://github.com/ionic-team/capacitor-testapp/issues/102
=> fix(filesystem): support writing files without scheme

status-bar/README.md
The example was using the old names
ref: https://github.com/ionic-team/capacitor-site/pull/215
=> docs(status-bar): Use Style instead of StatusBarStyle in examples

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
Filesystem plugin is not requesting permission for public directories, but instead requesting them for non public directories (where is not needed)
=> fix(filesystem): not requesting permission on public directories

filesystem/ios/Plugin/Filesystem.swift, filesystem/ios/Plugin/FilesystemPlugin.swift, filesystem/src/web.ts
Android allowed using file urls when no directory was passed.
This also allows absolute file urls on iOS and web platforms when no directory is passed instead of using a default directory
closes https://github.com/ionic-team/capacitor-plugins/issues/240
=> feat(filesystem): Allow the use of absolute urls on iOS and web

local-notifications/ios/Plugin/LocalNotificationsPlugin.swift
This PR disables the new [Capacitor v3 automatic date serialization](https://github.com/ionic-team/capacitor/pull/4177) in the iOS local-notifications plugin.
=> fix(local-notifications): Opt out of Capacitor date serialization

local-notifications/README.md, push-notifications/README.md
This PR adds notes for dealing with common issues related to handling push and local notifications:
- How to handle notifications during Doze
- Tips on testing the application during development
A note is also added to clarify that silent push notifications, and background (app is killed) data-only notifications are NOT supported in this plugin. Links to more documentation on platform specific workarounds are included.
closes: ionic-team/capacitor-plugins#200
closes: ionic-team/capacitor#3500
=> docs(push/local-notifications): Adding information about common notification issues

local-notifications/README.md
It's missing the configurations options from https://capacitorjs.com/docs/apis/local-notifications#local-notifications-configuration-android-only
=> docs(local-notifications): Add configuration section

geolocation/README.md
added missing => to printCurrentPosition  function
=> docs(geolocation): use proper function syntax on example

filesystem/README.md, local-notifications/src/web.ts
During `checkPermissions`, check to see if the Notifications API is supported by the browser and throws `unavailable` if not.
Closes: https://github.com/ionic-team/capacitor-plugins/issues/254
=> fix(local-notification): Throw unavailable if Notification API not supported

keyboard/ios/Plugin/Keyboard.m
depends on https://github.com/ionic-team/capacitor/pull/4309
=> chore(keyboard): Use call accessors instead of deprecated from CAPPlugin

haptics/README.md
Capacitor v3 has deprecated `HapticsImpactStyle` in favor of `ImpactStyle` but the docs were still using the old syntax. VSCode suggested the change but it would be nice of the docs mentioned this change especially as developers migrate from v2 to v3.
=> docs(haptis): Update README example to use ImpactStyle

filesystem/README.md, filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java, filesystem/ios/Plugin/FilesystemPlugin.swift, filesystem/src/definitions.ts
This PR makes `Filesystem.stat` return `ctime` and `mtime` in milliseconds iOS, bringing it in line with Android.
closes: https://github.com/ionic-team/capacitor-plugins/issues/313
=> fix(filesystem): Convert stat ctime/mtime timestamp to milliseconds

splash-screen/README.md, splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenConfig.java, splash-screen/ios/Plugin/SplashScreen.swift, splash-screen/ios/Plugin/SplashScreenConfig.swift
launchAutoHide was not working on iOS
also the PR changes the default splash value from 0 to 500ms so the splash always shows
and update the docs accordingly
closes https://github.com/ionic-team/capacitor-plugins/issues/270
closes https://github.com/ionic-team/capacitor-plugins/issues/317
closes https://github.com/ionic-team/capacitor-plugins/issues/300
=> fix(splash-screen): launchAutoHide not working on iOS

keyboard/README.md, keyboard/ios/Plugin/Keyboard.m, keyboard/src/definitions.ts
Default will be the default as, at the moment, we are preventing the keyboard style to change based on the device appearance.
Users can still change the values programmatically to any of the three possible values (dark, light or default), and the configuration allows to set to always light or always dark if their app doesn't react to device appearance changes.
closes https://github.com/ionic-team/capacitor-plugins/issues/318
=> feat(keyboard): Add default style option for setStyle

clipboard/src/index.ts, clipboard/src/web.ts
On iOS the the Clipboard API requires user interaction, the way the plugin is initialized makes the first method invocation to lose the user gesture and throw `NotAllowedError`.
By not using the promise on `registerPlugin`, the gesture is properly forwarded in first invocation
reference
https://forum.ionicframework.com/t/capacitor-3-clipboard-error/207576/5
=> fix(clipboard): prevent NotAllowedError on first method invocation

local-notifications/ios/Plugin/LocalNotificationsHandler.swift, local-notifications/ios/Plugin/LocalNotificationsPlugin.swift
extra was not being returned because it needed to be coerced, but also because userInfo was split into `cap_schedule` and `cap_extra`.
So reused `makePendingNotificationRequestJSObject` as it was already handling `cap_schedule` and `cap_extra` to generate the notification of `makeNotificationRequestJSObject`
closes https://github.com/ionic-team/capacitor-plugins/issues/337
=> fix(local-notifications): extra not being returned on notification events

dialog/ios/Plugin/DialogPlugin.swift
According to Apple's HIG, cancel button should always be on the left, but we put it in the right.
closes https://github.com/ionic-team/capacitor-plugins/issues/344
=> fix(dialogs): put cancel button of confirm/prompt on the left

storage/README.md
Add `async` to `setName` example.
=> doc(storage): add async to setName example function

push-notifications/ios/Plugin/PushNotificationsHandler.swift
- Renames `extra` back to `data`
- Remove `actionTypeId` and `attachments`
- Adds back `subtitle` and `badge`
closes: https://github.com/ionic-team/capacitor-plugins/issues/332
=> fix(push-notifications): proper return of push notification object properties

keyboard/ios/Plugin/Keyboard.h, keyboard/ios/Plugin/Keyboard.m
This branch updates the import statements in the Keyboard plugin. Since Capacitor is a separate framework, its headers should be imported with qualified brackets, `<>`, instead of quotes. (It was also inconsistently using both formats) It's a quirk of the build process that the quoted form worked and can cause the podspec to fail validation.
=> fix(iOS): header imports from Capacitor framework

filesystem/README.md, filesystem/src/definitions.ts, filesystem/src/web.ts
As it's not available con Android versions lower than `O`
closes https://github.com/ionic-team/capacitor-plugins/issues/355
=> fix(filesystem): Make ctime optional

.github/workflows/ci.yml
`push` event only contains last commit changes, so making it run on all branches is self-defeating as on every commit will run tests on the packages that changed on that commit and not on the whole PR, which might make us miss commits that broke the CI if last executed commit didn't break it but a previous one did.
But keep it for main branch as we sometimes push things directly.
Change `pull_request_target` to `pull_request` as we want to test the changes on the PR commit, not on the target commit.
=> chore: Run CI on push to main or pull_request

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
the call is never retrieved but passed to the methods that need it, so it shouldn't be saved and also saveCall is deprecated
=> fix(camera): Remove unused saveCall

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Use the same string errors for iOS and Android when users deny permission requests
=> feat(camera): Use same error messages for permission deny

scripts/update-all.mjs
update-all script is updating to latest `@next` tag, but should use `@latest` now since capacitor 3 is final
also make it update devDependencies too
=> chore: Make update-all script to use latest

geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/376
=> fix(geolocation): Make getCurrentPosition return only once

camera/ios/Plugin/CameraExtensions.swift
Hi again 🤓 
My [earlier PR](https://github.com/ionic-team/capacitor-plugins/pull/448) was made because resizing images on iOS by specifying `width` and `height` doesn't work, so I thought the logic was missing, but it turns out it just doesn't work.
To test the bug, just add `width` and `height` options to the TestApp Camera page. Notice it does not preserve the aspect ratio. This PR fixes that.
=> fix(camera): fix photo resizing on iOS

app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java
where available, use getLongVersionCode as versionCode is deprecated
closes https://github.com/ionic-team/capacitor-plugins/issues/363
=> fix(app): use alternative to deprecated versionCode

push-notifications/README.md, push-notifications/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/350
=> docs(push-notifications): Add missing information on types

camera/ios/Plugin/CameraPlugin.swift
.path removes the scheme and hostname from the url, use absoluteString instead
closes https://github.com/ionic-team/capacitor-plugins/issues/501
=> fix(camera): Return the full webPath

splash-screen/ios/Plugin/SplashScreen.swift
Instead of creating a UIImageView with the same image as the launch storyboard, use the own launch storyboard view, so it can be edited to add other images, text or anything that is allowed in a launch storyboard and will be shown on both the launch storyboard and the splash-screen plugin
closes https://github.com/ionic-team/capacitor-plugins/issues/414
=> feat(splash-screen): Use Launch Storyboard for iOS splash 

local-notifications/rollup.config.js
I tried to use the latest version of the Local Notifications plugin by linking the `dist/plugin.js` and it turns out the configuration of this plugin is wrong. Instead of using `capacitorLocalNotifications` it was set to `capacitorHaptics` and instead of using the globals `capacitorExports` it was using `capacitorLocalNotifications`.
Console output:
```
capacitor-local-notifications.js:150 Uncaught ReferenceError: capacitorLocalNotifications is not defined
at capacitor-local-notifications.js:150
(anonymous) @ capacitor-local-notifications.js:150
```
=> fix(local-notifications): Fixed wrong rollup config

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java, camera/android/src/main/java/com/capacitorjs/plugins/camera/ExifWrapper.java, camera/android/src/main/java/com/capacitorjs/plugins/camera/ImageUtils.java
Pass the exif object to ImageUtils and correct the orientation in it instead of in the file path to prevent problems with content urls.
closes https://github.com/ionic-team/capacitor-plugins/issues/524
=> fix(camera): Properly reset orientation exif if corrected

splash-screen/ios/Plugin/SplashScreen.swift
We are using the hardcoded `LaunchScreen` value for the splash screen plugins, but users can change the launch storyboard by changing the value of `UILaunchStoryboardName` entry in the info.plist, so we should read the value, and if present use it instead of the hardcoded `LaunchScreen`
closes https://github.com/ionic-team/capacitor-plugins/issues/534
=> fix(splash-screen): Use configured storyboard instead of hardcoded value

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Hopefully on all devices, but maybe not all, I tested on android 5, 7, 9 and 11 without problems
With the move from request codes to activity launcher the code no longer catch the security exception, so now will always create a copy of the file and edit the copy instead of trying to edit the returned content urls, which could cause security exceptions in some devices.
Also calls `grantUriPermission` for the url passed to the edit intent, shouldn't be necessary, but on Android 11 it doesn't work without it.
closes https://github.com/ionic-team/capacitor-plugins/issues/306
closes https://github.com/ionic-team/capacitor-plugins/issues/307
=> fix(camera): Make allowEdit work on all devices

camera/android/src/main/java/com/capacitorjs/plugins/camera/ImageUtils.java
On Android <24 an error is thrown on the correctOrientationOlder method if the image has no orientation information. 
Since we are using AndroidX's ExifInterface we no longer need the correctOrientationOlder because AndroidX is supposed to be backward compatible, so should be handling this already.
I've verified that the error is no longer shown on my android 5 device.
=> fix(camera): avoid error if image has no orientation

storage/ios/Plugin/Storage.swift
In order to use StoragePlugin in the native context the StorageConfiguration inits needs to be public
=> feat(storage): make StorageConfiguration init public

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
If not returning the image uri and not saving the image to gallery, remove the image file that was created when launching the camera intent.
Also, if returning the uri, don't resave the camera image into caches folder, reuse the path passed to the camera intent to avoid duplication of files.
closes https://github.com/ionic-team/capacitor-plugins/issues/431
=> fix(camera): cleanup camera images if not needed

push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/NotificationChannelManager.java
Channel id, name and importance are mandatory, the app crash if not provided, better return an error if not provided.
=> fix(push-notifications): Throw errors if missing mandatory channel fields

geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java
By checking `isLocationEnabled` instead of relying on `isLocationAvailable`, we can throw an error if the location is disabled by the user, and not having the `onLocationAvailability` callback workarounds the google play services bug that makes `isLocationAvailable()` to be always false.
=> feat(geolocation): Throw error if location is disabled

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
If the app gets killed when the camera intent is launched, the settings go back to the default values.
This PR sets the settings again from the restored plugin call.
=> fix(camera): set settings again on callbacks

storage/README.md, storage/android/src/main/java/com/capacitorjs/plugins/storage/StoragePlugin.java, storage/ios/Plugin/StoragePlugin.m, storage/ios/Plugin/StoragePlugin.swift, storage/src/definitions.ts, storage/src/web.ts
to remove data prefixed with `_cap_` that can't be removed otherwise after being migrated
android didn't use the prefix, so the code does nothing there
closes https://github.com/ionic-team/capacitor-plugins/issues/541
=> feat(storage): Add removeOld function

camera/README.md, camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java, camera/ios/Plugin.xcodeproj/project.pbxproj, camera/ios/Plugin/CameraPlugin.swift, camera/ios/Plugin/CameraTypes.swift, camera/ios/Plugin/ImageSaver.swift, camera/src/definitions.ts, camera/src/web.ts
At the moment on iOS, if the user doesn't grant the gallery permission, we return the image even if it fails to save it to the gallery.
On Android, if the user doesn't grant the gallery permission in enters in an infinite loop of requesting the permission.
This PR unify the behaviour so on Android it returns the image even if it failed to save to to the gallery and prevents the infinite loop.
Additionally, on the returned object, it adds a saved property that will tell the user if the image was saved to the gallery or not.
closes https://github.com/ionic-team/capacitor-plugins/issues/593
=> feat(camera): Return if image was saved to gallery

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
If saveToGallery is set but you edit the image it's not being able to save it because imageEditedFileSavePath is being set to a content url, this PR changes it to use the original absolute path.
=> fix(camera): saveToGallery for edited images

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotification.java, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationSchedule.java
return the original js object instead of the native object string representation
closes https://github.com/ionic-team/capacitor-plugins/issues/406
=> fix(local-notifications): return schedule on as object

splash-screen/README.md
The JS code examples are missing `await` statements for functions that return promises.
=> Add missing `await` statement

haptics/README.md, haptics/ios/Plugin/Haptics.swift, haptics/ios/Plugin/HapticsPlugin.swift, haptics/src/definitions.ts
Making it a feature despite it's technically a fix since the duration works in other platforms.
Implements duration for iOS 13+, where available, rely on the old vibration without duration where not available.
closes https://github.com/ionic-team/capacitor-plugins/issues/316
=> feat(haptics): Implement duration for vibration on iOS 13+

geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java, geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java
At the moment we are always getting a new location instead of checking if the latest cached location is newer than maximumAge.
This PR reads maximumAge and check the cached locations (for all providers) and returns a cached value if newer than maximumAge, otherwise it gets current location as usual.
closes https://github.com/ionic-team/capacitor-plugins/issues/609
=> fix(geolocation): return cached location if newer than maximumAge

network/src/web.ts
If network plugin is imported in SSR context, it fails to compile because window is not available on SSR, so add a window check before adding the event listeners
closes https://github.com/ionic-team/capacitor-plugins/issues/669
=> fix(network): Don't add window event listeners if there is no window

camera/src/web.ts
capture shouldn't be used in the multiple picker as it shows the camera UI instead of the image picker.
closes https://github.com/ionic-team/capacitor-plugins/issues/686
=> fix(camera): Remove capture attribute from multiple photo picker

camera/ios/Plugin/CameraPlugin.swift
The plugin is returning the exif of the first picture for all, make it return the real image exif.
closes https://github.com/ionic-team/capacitor-plugins/issues/707
=> fix(camera): Return proper exif when picking multiple images

device/ios/Plugin/DevicePlugin.swift
isVirtual is false on simulators run on M1 macs because it's none of those architectures, use `targetEnvironment(simulator)`  instead
closes https://github.com/ionic-team/capacitor-plugins/issues/720
=> fix(device): isVirtual is false on M1 simulators

splash-screen/ios/Plugin/SplashScreen.swift
updateSplashImageBounds is called multiple times and the first two are before the app window is set as key window, so the first check returns a nil, in that case just pick the first window.
=> fix(splash-screen): pick first window when there is no key window

text-zoom/src/index.ts
we are declaring the implementations like this on all plugins except this one, so I think it was a mistake and it makes web to import iOS code despite it's not being used
I've tested on iOS and the plugin keeps working after the change, so I think it can be lazy loaded like the others.
closes https://github.com/ionic-team/capacitor-plugins/issues/717
=> fix(text-zoom): Lazy load iOS implementation

filesystem/src/web.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/66
=> fix(filesystem): Throw errors instead of strings

share/README.md, share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java, share/ios/Plugin/SharePlugin.m, share/ios/Plugin/SharePlugin.swift, share/src/definitions.ts, share/src/web.ts
At the moment we reject if share is not available and an user tries to share, but it would be more useful if they can check if sharing is available in the browser/device beforehand to show or hide sharing buttons accordingly.
iOS and Android just return true.
closes https://github.com/ionic-team/capacitor-plugins/issues/747
=> feat(share): Add canShare method to check availability

action-sheet/tsconfig.json, app-launcher/tsconfig.json, app/tsconfig.json, browser/tsconfig.json, camera/tsconfig.json, clipboard/tsconfig.json, device/tsconfig.json, dialog/tsconfig.json, filesystem/tsconfig.json, geolocation/tsconfig.json, haptics/tsconfig.json, keyboard/tsconfig.json, local-notifications/tsconfig.json, motion/tsconfig.json, network/tsconfig.json, push-notifications/tsconfig.json, screen-reader/tsconfig.json, share/tsconfig.json, splash-screen/tsconfig.json, status-bar/tsconfig.json, storage/tsconfig.json, text-zoom/tsconfig.json, toast/tsconfig.json
esm source maps point to the .ts files, but we don't distribute them
This PR makes typescript compiler to inline the plugins code into the source maps as rollup is doing for cjs and iife 
closes https://github.com/ionic-team/capacitor-plugins/issues/755
=> fix: inline source code in esm map files

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
we are calling processPickedImages(imageUri) twice, there is no need
this should decrease memory usage and increase speed when selecting multiple pictures
=> fix(camera): process picked image only once

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Some gallery apps return the data in `data.getData()` instead of in `data.getClipData()` when a single picture is selected, handle that case.
=> fix(camera): return single picture on pickImages

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Add support for 1 Gallery and other gallery apps that return a file url instead of a content url.
Since the urls are read only when we try to save it throws an error, in that case we need to create a temporary file as we do for content urls 
closes https://github.com/ionic-team/capacitor-plugins/issues/722
=> feat(camera): Support for 1 Gallery app

toast/README.md, toast/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/pull/781
=> docs(toast): Fix typo in position description

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
by default `toUpperCase` uses the device locale, which can cause undesired values in certain languages, pass `Locale.ROOT` to get the expected value
closes https://github.com/ionic-team/capacitor-plugins/issues/811
=> fix(camera): Use Locale.ROOT on toUpperCase

splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreenPlugin.java
some spinner styles don't work when the device is using certain locales, use Locale.ROOT in toLowerCase to fix it
=> fix(splash-screen): Use Locale.ROOT on toLowerCase

app-launcher/README.md, app/README.md, clipboard/README.md, screen-reader/README.md, storage/README.md
Because `alert()` only accept one argument, the second argument `value` will be ignored, and thus the `value` will not be shown on screen in the original example.
=> docs: replace alert with console.log in example section

camera/ios/Plugin/CameraPlugin.swift
At the moment we are returning the image at the same time that we call dismiss, that causes problems if the user tries to present another native modal with the result (i.e. share plugin).
This PR changes the code to return the image once dismiss is completed, so it's safe to present other modals.
=> fix(camera): Return the image on dismiss completion

app/android/src/main/java/com/capacitorjs/plugins/app/AppPlugin.java
build value was incorrect for Android >= P devices if `versionCodeMajor` was specified in the AndroidManifest.xml, this PR resolves that problem by getting only the int part of `getLongVersionCode`, which corresponds to the deprecated `versionCode`.
Also uses `PackageInfoCompat` class to avoid the deprecation warning on `versionCode` usage.
closes https://github.com/ionic-team/capacitor-plugins/issues/838
=> fix(app): get correct build value

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationSchedule.java
Replace `CapConfig` with `PluginConfig`
Replace `DateUtils.YEAR_IN_MILLIS` with it's value
closes https://github.com/ionic-team/capacitor-plugins/issues/844
=> refactor(local-notifications): replace deprecated code

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java
There are no alternatives for those folders, they are just not accessible anymore on Android 10+.
It's already documented on the plugin directory options, so this PR just silence the warnings.
closes https://github.com/ionic-team/capacitor-plugins/issues/841
=> chore(filesystem): silence deprecation warnings

haptics/android/src/main/java/com/capacitorjs/plugins/haptics/Haptics.java
Suppress deprecation warning on `Context.VIBRATOR_SERVICE`
Also, replace hardcoded 26 with `Build.VERSION_CODES.O`
closes https://github.com/ionic-team/capacitor-plugins/issues/842
=> refactor(haptics): replace deprecations

share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/690
=> fix(share): avoid crash when targeting SDK 31

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/901
=> fix(filesystem): Prevent android crash on invalid base64 write

filesystem/README.md, filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java, filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java, filesystem/ios/Plugin/FilesystemPlugin.swift, filesystem/src/definitions.ts, filesystem/src/web.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/252
=> feat(filesystem): Return path of copied file

filesystem/src/web.ts
=> fix(filesystem): web appendFile with base64 data

google-maps/ios/Plugin/Map.swift
In XCode 13 (Swift 5.5) this is not an issue. On XCode 12 (Swift 5.4), the ScrollView.bounds variables are `CGFloat` and not `Double` so the compiler gets mad at us
=> hotfix(maps): Cast item.bounds to compare as Double instead of CGFloat for XCode 12 support

push-notifications/README.md, push-notifications/src/definitions.ts
This was documented as available on version 2.0.0 before it was decided to use version 4.0.0 as next major version instead of 2.0.0
=> chore(push-notifications): Correct plugin version

local-notifications/README.md, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/TimedNotificationPublisher.java
Use set/setAndAllowWhileIdle when exact notifications are not allowed on SDK >= 31
=> fix(local-notifications): Handle case of not allowed exact notifications

keyboard/README.md, keyboard/src/definitions.ts
closes: https://github.com/ionic-team/capacitor-plugins/issues/918
=> chore(keyboard): Using KeyboardStyle in plugin TS declaration

keyboard/README.md
Remove the docgen-config tags to use manually generated configuration docs and examples.
Use the enum instead of the enum value in the .ts example.
=> chore(keyboard): Switch to manual config

browser/ios/Plugin/BrowserPlugin.swift
It's deprecated and no longer needed as on iOS 13+ it's always supported
=> chore(browser): remove supportsPopover() usage

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java, local-notifications/android/src/main/res/drawable/ic_transparent.xml
In https://github.com/ionic-team/capacitor/pull/5682 I removed unused Capacitor resources, but ic_transparent was being used in local-notifications plugin.
I've added the ic_transparent to the plugin as if the plugin is using it it should be created here instead of in Capacitor.
Removed the R import so it finds the drawable instead of searching inside Capacitor.
=> chore(local-notifications): Create ic_transparent drawable

keyboard/ios/Plugin/Keyboard.m
The status bar size change listener was added to resize in case the status bar changed to the in-call status bar, which used to be 40 points of height, but since iOS 13 the status bar size doesn't change anymore, so this code is no longer relevant.
=> chore(ios): Remove code that checks status bar height

push-notifications/README.md, push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java, push-notifications/src/definitions.ts
Fixes an issue where it was not possible to delete individual notifications on Android.
closes: https://github.com/ionic-team/capacitor-plugins/issues/740
=> fix(push-notifications): use id and tag for canceling active notification

google-maps/android/build.gradle, scripts/publish-android.sh
make gradle changes to include the native publish for google maps
also changed the url where the publish script gets latest capacitor version to get latest 3.x version as main have the 4.0.0 beta
=> chore(google-maps): Add native publish

geolocation/README.md, geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/Geolocation.java, geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java, geolocation/src/definitions.ts
This PR will check the Android location services and will throw an error in `checkPermissions` and `requestPermissions` if it's disabled, bringing the behavior inline with iOS.
closes: https://github.com/ionic-team/capacitor-plugins/issues/1035
=> fix(geolocation): reject checkPermissions / requestPermissions if location services are disabled

keyboard/README.md, keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/KeyboardPlugin.java, keyboard/ios/Plugin/Keyboard.m, keyboard/ios/Plugin/KeyboardPlugin.m, keyboard/src/definitions.ts
Adds a function for getting the current KeyboardResize mode on iOS.
Can be tested with: https://github.com/ionic-team/capacitor-testapp/pull/408
=> feat(keyboard): add getResizeMode function

share/README.md, share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
Reject if the file is in a non shareable location instead of crashing.
Also add a section in docs with information about how to make other locations shareable.
=> fix(share): Prevent crash on no shareable files

filesystem/src/web.ts
readdir now returns an object instead of just the file name, so we need to get the file name from the object to properly delete folder content
closes https://github.com/ionic-team/capacitor-plugins/issues/1111
=> fix(filesystem): failing to remove folder content on rmdir

camera/README.md, camera/ios/Plugin/CameraPlugin.m, camera/ios/Plugin/CameraPlugin.swift, camera/src/definitions.ts, camera/src/web.ts
The new methods introduced on https://github.com/ionic-team/capacitor-plugins/pull/1125 will be available in next 4.1.0 release, not in 4.0.0, update docs accordingly.
Add missing `removeAllListeners` method in `CameraPlugin.m`, calling it errors at the moment.
Removed `and below` from `iOS 13 and below` error messages since we don't support older versions.
Also noticed that `photoLibraryDidChange` is called every time a change is made in the user's photo library, not only when the limited selection is changed (i.e. if the user takes a new picture or deletes it), so `limitedLibrarySelectionChanged` event is fired for every change and not for selection changes, so maybe the name should be changed to `photoLibraryDidChange` (to match the native name). Current name is misleading and also the …
=> fix(camera): remove listener methods

filesystem/README.md
Add information to `@capacitor/filesystem` on how to make application files visible within the iOS Files app.
=> docs(filesystem): opting into the Files app

google-maps/src/web.ts
This PR adds back the missing marker `draggable` property for web.
=> fix(google-maps): adding missing marker draggable property for web

camera/README.md, camera/ios/Plugin/CameraPlugin.swift, camera/src/definitions.ts
closes https://github.com/ionic-team/capacitor-plugins/issues/1158
Note: On iOS 14 it's not possible to know when the limited image picker is closed as the method with the completion is only available for iOS 15.
So, for being able to return the pictures, it relies on the `PHPhotoLibraryChangeObserver`. But if the users calls `pickLimitedLibraryPhotos` and then doesn't change the selection, `pickLimitedLibraryPhotos` will not reject nor resolve until some change is made on the user's photo gallery in the future.
Not sure if we want that behavior or if it would be better to just return the pictures on iOS 15+ and document that on iOS 14 it returns an empty array?
=> fix(camera): make pickLimitedLibraryPhotos return photos

filesystem/src/web.ts
Some SO comments say this check is a bit lax, but the regular expression hits max stack size exceeded and I can't find a better way that doesn't require regular expressions (tested other expressions and using match instead of test and also get max stack size exceeded).
I've been testing this check and comparing with iOS results and they both return true/false for the same string I've tested, so I think it's ok to use.
Also, we already use the btoa/atob on append call.
closes https://github.com/ionic-team/capacitor-plugins/issues/1138
=> fix(filesystem): Avoid max stack size exceeded on base64 check

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java, local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/TimedNotificationPublisher.java
Fixes an issue where `on` and `every` notification schedules did not show the current notification time.
closes: https://github.com/ionic-team/capacitor-plugins/issues/433
=> fix(local-notifications): Showing correct scheduled notification time

.github/bot.yml, .github/ionic-issue-bot.yml
Add ionic-issue-bot to add triage label to new issues and lock closed issues
Removed the triage step from the old bot since it's not working
=> chore(ci): Add ionic-issue-bot

google-maps/README.md
the maps custom element is `capacitor-google-map`, not `capacitor-google-maps`
=> docs(google-maps): fix typo in angular example

google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt, google-maps/ios/Plugin/Map.swift
Save the image/bitmap without resizing and resize when the icon is going to be used with the configured size
closes https://github.com/ionic-team/capacitor-plugins/issues/1201
=> fix(google-maps): allow to resize icons with same image

google-maps/README.md, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/GoogleMapConfig.kt, google-maps/ios/Plugin/GoogleMapConfig.swift, google-maps/ios/Plugin/Map.swift, google-maps/src/definitions.ts
Make GoogleMapConfig extend `google.maps.MapOptions` son any javascript SDK config option can be used on web.
Also implement [styles](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.styles) for iOS and android.
closes https://github.com/ionic-team/capacitor-plugins/issues/946
closes https://github.com/ionic-team/capacitor-plugins/issues/992
closes https://github.com/ionic-team/capacitor-plugins/issues/1017
=> feat(google-maps): Add more config options

google-maps/src/map.ts
There is a bug on ionic/vue that makes custom elements have 0 size on mounted, and probably some other edge cases that could cause the map to have 0 size.
This PR will retry trying to get the google maps custom element size for 3 seconds every 100ms to solve those problems and warn if it still couldn't get the map size after the 3 seconds.
closes https://github.com/ionic-team/capacitor-plugins/issues/1102
=> fix(google-maps): Retry getting the map size if it's 0

.github/workflows/publish-ios.yml
The iOS plugin podspecs appear to have no difference between the `native-publish` branch and main. @carlpoole is working on utilizing the same strategy with the android plugins as was done in https://github.com/ionic-team/capacitor/pull/6022 to publish off of main (or any other branch) so we don't have to keep a long-lived branch in sync to publish our official plugins.
=> chore(ios): Update publish-ios.yml to no longer use native-publish branch

.github/workflows/publish-android.yml, action-sheet/android/build.gradle, action-sheet/package.json, app-launcher/android/build.gradle, app/android/build.gradle, browser/android/build.gradle, camera/android/build.gradle, clipboard/android/build.gradle, device/android/build.gradle, dialog/android/build.gradle, filesystem/android/build.gradle, geolocation/android/build.gradle, google-maps/android/build.gradle, google-maps/src/map.ts, haptics/android/build.gradle, keyboard/android/build.gradle, local-notifications/android/build.gradle, network/android/build.gradle, preferences/android/build.gradle, push-notifications/android/build.gradle, screen-reader/android/build.gradle, scripts/.gitignore, scripts/android/publish-module.gradle, scripts/android/publish-root.gradle, scripts/publish-android.sh, share/android/build.gradle, splash-screen/android/build.gradle, status-bar/android/build.gradle, text-zoom/android/build.gradle, toast/android/build.gradle
Similarly to https://github.com/ionic-team/capacitor/pull/6022 this pull request adds the native publication scripts into main and eliminates the need for the `native-publish` branch in the capacitor-plugins repo.
The plugins use a separate ENV variable in the flow `CAP_PLUGIN_PUBLISH` to distinguish from Capacitor so it doesn't trigger the scripts inside the Capacitor core project and cause a gradle error.
- The publish-android job will now attempt to fully publish the plugin all the way to production if the script checks are successful.
- Updated the publication script to also support Kotlin plugins like google-maps.
=> chore(android): native artifact publish logic

google-maps/android/gradle.properties
https://github.com/ionic-team/capacitor-plugins/actions/runs/3422497029/jobs/5699974730#step:5:46
Metaspace error when trying to build and publish google-maps plugin. It is related to there not being enough memory allocated for the process.
I encountered this error locally when building too but it didn't happen all the time. It occurred during GitHub publish job and failed the build. This should help prevent the issue in the future. I tested locally a few times and couldn't reproduce the error after this.
=> chore(android): increase jvm mem size for building google-maps in gradle

google-maps/package.json
The types introduced in https://github.com/ionic-team/capacitor-plugins/pull/1233 come from @types/google-maps, but since they are a dev dependency, apps using the latest version of the plugin fail to build if they don't have @types/google-maps installed.
Making it a dependency fixes the build issue without users having to install @types/google-maps themselves.
closes https://github.com/ionic-team/capacitor-plugins/issues/1261
=> fix(google-maps): install google.maps types as dependency

splash-screen/ios/Plugin/SplashScreen.swift
Xcode 14 appends `.storyboard` to the storyboard name if the launch storyboard is changed from there, but then getting the storyboard from the name crashes if the name contains `.storyboard` extension.
So remove it in case it's there.
closes https://github.com/ionic-team/capacitor-plugins/issues/1253
=> fix(splash-screen): Remove extension from storyboard name

status-bar/README.md, status-bar/src/definitions.ts
Document that slide animation no longer works on iOS 15+ and a glitch that can happen on first show call
closes https://github.com/ionic-team/capacitor-plugins/issues/1238
=> docs(status-bar): Document animation problems on show/hide

google-maps/android/gradle.properties, scripts/publish-android.sh
This fixes the metaspace issue the android build CI ran into when it got to google-maps. The daemon was running out of memory and has negligible benefit in this flow, so I disabled it and it seems to have fixed the issue in conjunction with increasing the amount of memory the gooogle-maps plugin has to build. Tested locally publishing against maven snapshot repo.
=> chore(android): remove daemon and increase mem for google-maps build

.github/workflows/publish-ios.yml
Updates publish-ios.yml to use the working-directory of the plugin. Removes unneeded dependency caching and npm install.
=> chore(ci): Fix publish-ios.yml 

local-notifications/ios/Plugin/LocalNotificationsPlugin.swift
A new version of swiftlint was released that makes local-notifications plugin fail to lint because of body length of the LocalNotificationsPlugin class (see https://github.com/ionic-team/capacitor-plugins/pull/1303)
This PR ignores body length of the class.
=> chore(local-notifications): ignore body length lint error

share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
The `Intent.EXTRA_STREAM` should be put outside of the SDK_INT version check.
The `setDataAndType` originally started as `setData` and was changed to `setDataAndType` because it caused problems as calling `setData` resets the type.
`setData` was added to prevent a permission error that was being displayed on Android 10+ because the share dialog didn't have permission to preview the shared image. But we shouldn't have used `setData` nor replace it with `setDataAndType` later on. For granting the uri permission to the preview `setClipData` should be used instead.
closes https://github.com/ionic-team/capacitor-plugins/issues/1353
closes https://github.com/ionic-team/capacitor-plugins/pull/1371
=> fix(share): not sharing files on Android < 10

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationManager.java
See docs on RTC vs RTC_WAKEUP
https://developer.android.com/reference/android/app/AlarmManager#RTC
This simply updates RTC to RTC_WAKEUP so that the device wakes up when a local notification goes off and allowWhileIdle is true
=> Fix(local-notifications): adds RTC_WAKEUP if schedule.allowWhileIdle is true

google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt
This PR fixes #1357, where the touch position was being dispatched to the wrong y coordinate.
Sample reproduction: https://github.com/marlon-ionic/ng14-ssfcu-cap-map-sidemenu
=> fix(google-maps/android): dispatch touch events to correct y position

google-maps/README.md, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt, google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.m, google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift, google-maps/ios/Plugin/Map.swift, google-maps/src/implementation.ts, google-maps/src/map.ts, google-maps/src/web.ts
I've called it `getMapType` instead of the proposed `getMapTypeId` (google maps js SDK name) since we have a `setMapType` function and the native methods in google maps SDK are called `getMapType`.
Also returns our existing `MapType`  instead of the proposed `google.maps.MapTypeId` since they don't match.
closes https://github.com/ionic-team/capacitor-plugins/issues/1347
=> feat(google-maps): Add getMapType method

action-sheet/android/gradle.properties, app-launcher/android/gradle.properties, app/android/gradle.properties, browser/android/gradle.properties, camera/android/gradle.properties, clipboard/android/gradle.properties, device/android/gradle.properties, dialog/android/gradle.properties, filesystem/android/gradle.properties, geolocation/android/gradle.properties, google-maps/android/gradle.properties, google-maps/e2e-tests/android/gradle.properties, haptics/android/gradle.properties, keyboard/android/gradle.properties, local-notifications/android/gradle.properties, network/android/gradle.properties, preferences/android/gradle.properties, push-notifications/android/gradle.properties, screen-orientation/android/gradle.properties, screen-reader/android/gradle.properties, scripts/publish-android.sh, share/android/gradle.properties, splash-screen/android/gradle.properties, status-bar/android/gradle.properties, text-zoom/android/gradle.properties, toast/android/gradle.properties
Removes `android.enableJetifier` in all core plugins and in the publish script as its no longer needed for modern libraries.
=> feat(android): Removing enableJetifier

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/TimedNotificationPublisher.java
- Replace getParcelableExtra(String) with getParcelableExtra(String, Class<T>)
=> chore(android): fix local-notification deprecation warning

local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java
Move Deprecated `Bundle.get` call to it's own function and update.
=> chore(local-notifications): remove deprecated call

google-maps/README.md, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapMarker.kt, google-maps/ios/Plugin/Map.swift, google-maps/ios/Plugin/Marker.swift, google-maps/src/definitions.ts, google-maps/src/web.ts
This PR adds the `zIndex` property to Markers. It is also required to update the Maps Util Verion #1449
=> feat(google-maps): add zIndex to markers

clipboard/ios/Plugin/Clipboard.swift, network/ios/Plugin/Reachability.swift, toast/ios/Plugin/ToastLabel.swift
macos-12 image has been updated to use swiftlint 0.51.0 and it's making our lint to fail
I've run `npm run fmt` with swiftlint 0.51.0, so it hopefully fixes the lint problems
=> chore: format with swiftlint 0.51.0

google-maps/README.md, google-maps/android/build.gradle
for kotlin 1.8.x `kotlin-stdlib` should be used instead of `kotlin-stdlib-jdk7` or `kotlin-stdlib-jdk8`, replaced the dependency and also the default values for coreKTX and kotlin
=> chore(google-maps): Update default coreKTX and kotlin versions

.github/workflows/publish-latest.yml, .github/workflows/publish-npm-alpha.yml, .github/workflows/publish-npm-beta.yml, .github/workflows/publish-npm-dev.yml, .github/workflows/publish-npm-latest.yml, .github/workflows/publish-npm-nightly.yml, .github/workflows/publish-npm-rc.yml, package.json
See https://github.blog/2023-04-19-introducing-npm-package-provenance/
This also cleans up the following in the GitHub Actions workflows:
* npm 9.5 is now included with node 18
* use setup-node to [cache package data](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data)
* use setup-node to configure npm token via [NODE_AUTH_TOKEN](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm)
=> chore(ci): enable npm package provenance

google-maps/README.md
The dependency name is Google-Maps-iOS-Utils, not Google-Maps-Utils-iOS
=> docs(google-maps): fix typo in dependency name

filesystem/android/build.gradle, geolocation/android/build.gradle
This PR adds the `androidx.appcompat:appcompat` library to the plugins where it is missing (`filesystem` and `geolocation`) so that `assembleRelease` does not throw errors related to resource linking.
=> fix(android): add appCompat libraries for maven releases

google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMap.kt
This PR adds a null check to the addMarkers method for Android. `googleMap` in line 183 can be null here, when the map is destroyed but the method is still processing. Then `googleMapMarker` is also null which crashs in line 191.
Closes https://github.com/ionic-team/capacitor-plugins/issues/1570
=> fix(google-maps): Added null check to addMarkers method

google-maps/README.md
According to:
https://github.com/ionic-team/capacitor-plugins/blob/dc5acf07d60293d53dbb33dbfb61620fc05572c6/google-maps/android/build.gradle#L93
The `kotlin_version` variable is being used as the version of `org.jetbrains.kotlin:kotlin-stdlib`, not `org.jetbrains.kotlin:kotlin-stdlib-jdk7`.
=> docs(google-maps): fix typo

CONTRIBUTING.md, package.json, scripts/lib/subprocess.mjs
closes https://github.com/ionic-team/capacitor-plugins/issues/774
=> fix: Make toggle-local work on windows

splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java
related to https://github.com/ionic-team/capacitor-plugins/pull/1640
=> fix(splash-screen): Avoid crash when splash resources not found

google-maps/src/map.ts
Some listeners are missing from `removeAllMapListeners()` which results in them being called even after calling `removeAllMapListeners()`.
=> fix(google-maps): Add missing listeners to removeAllMapListeners()

.github/bot.yml, .github/ionic-issue-bot.yml
Improve the needs reproduction bot message
Also add a message when `type: bug` label is added as feedback to users.
=> chore: Improve bot message for requesting reproductions

package.json
This stops all the plugins getting a new publish whenever only a few have changed.
=> chore: fix all plugins always publishing

camera/README.md, camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
closes https://github.com/ionic-team/capacitor-plugins/issues/1701
=> fix(camera): Request only the permissions needed by Android version

google-maps/README.md, google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPlugin.kt, google-maps/e2e-tests/src/pages/Map/CreateAndDestroyMap.tsx, google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.m, google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift, google-maps/ios/Plugin/Map.swift, google-maps/src/implementation.ts, google-maps/src/map.ts, google-maps/src/web.ts
Closes https://github.com/ionic-team/capacitor-plugins/issues/1600
=> feat(google-maps): Added feature to disable touch events on map

filesystem/README.md, filesystem/ios/Plugin/Filesystem.swift, filesystem/src/definitions.ts, filesystem/src/web.ts
Closes: #1716 
This PR fixes the behavior on web for `downloadFIle` to match the other plugin methods where it writes the file to the IndexedDB instead of directly downloading it to the `Downloads` folder.
=> fix(filesystem): download file on web to IDB instead of Downloads folder

google-maps/ios/Plugin/CapacitorGoogleMapsPlugin.swift, google-maps/src/web.ts
`setMapType` is not working for `MapType.Normal` because `Normal` doesn't exist on google maps and we replace it with `roadmap`, but the check where we compare with `Normal` is not working because we compare after the lowercase. 
So changed `setMapType` to compare the `MapType.Normal` with the non lowercased value.
Also noticed that `getMapType` was returning the google maps values, which are lowercased, so they don't match with the types and return undefined, so changed them to return our values with the first letter capitalized.
closes https://github.com/ionic-team/capacitor-plugins/issues/1726
=> fix(google-maps): problems on get/setMapType on web

filesystem/ios/Plugin/Filesystem.swift
`URLSession` doesn't error if there is a http error, so check the response code and if it's not 2XX reject the call.
I made the error match the Android error message.
closes https://github.com/ionic-team/capacitor-plugins/issues/1698
=> fix(filesystem): catch http errors on downloadFile

package.json
Despite we have `"typescript": "~4.1.5"` in all plugin's package.json, 5.2.2 is being installed in the root and causing lint issues because typescript 5.2 removed something that we don't use but something we use might be using.
This PR adds `"typescript": "~4.1.5"` entry in the root package.json so it uses that version for all packages and lint gets fixed.
=> chore: force typescript 4.1

.npmrc, package.json
Current npm script tries to publish each plugin even if they aren't needed. This PR fixes that by using Lerna with provenance turned on via `.npmrc`
See https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598 for example/info
=> chore: fix ci latest publish trying to publish all plugins

.npmrc, package.json
See: https://github.com/ionic-team/capacitor-plugins/pull/1802
=> chore: fix ci latest publish trying to publish all plugins (5.x)

google-maps/android/src/main/java/com/capacitorjs/plugins/googlemaps/CapacitorGoogleMapsPoint.kt
Fix for marker point image coordinate, which is used to change anchor.
closes https://github.com/ionic-team/capacitor-plugins/issues/1812
=> fix(google-maps): correctly apply CapacitorGoogleMapsPoint y value

google-maps/ios/Plugin/Map.swift
closes https://github.com/ionic-team/capacitor-plugins/issues/1667
=> fix(google-maps): use URLSession for remote iconUrl on iOS

.github/workflows/dev-releases-for-pr.yml
Going to leave `--dry-run` on for now to make sure its behaving correctly on Github Actions, this did work fine using `act` locally.
=> chore(ci): create dev releases for non-draft PRs

geolocation/README.md, google-maps/README.md
Removing `NSLocationAlwaysUsageDescription` in exchange for `NSLocationAlwaysAndWhenInUseUsageDescription` as its now [deprecated](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription).
=> docs(google-maps/geolocation)!: Removing deprecated usage descriptions for iOS

share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java
This is the simpler solution I've found for addressing Android 14 changes.
I think `FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT` is safe to use because we only use the pending intent for getting the package of the app the user selected to share, we null the value right before the share starts so if somebody managed to get our `BroadcastReceived` it will have no effect.
But if somebody thinks this is unsafe I can try some different approach that doesn't use `FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT`.
=> fix(share): Address Android 14 changes

app/ios/Plugin/AppPlugin.m, browser/ios/Plugin/BrowserPlugin.m, keyboard/ios/Plugin/KeyboardPlugin.m, local-notifications/ios/Plugin/LocalNotificationsPlugin.m, network/ios/Plugin/NetworkPlugin.m, push-notifications/ios/Plugin/PushNotificationsPlugin.m, screen-orientation/ios/Plugin/ScreenOrientationPlugin.m, screen-reader/ios/Plugin/ScreenReaderPlugin.m
removeAllListeners is going to work out of the box on Capacitor 6, no need for additional declarations
=> refactor(ios): remove removeAllListeners methods

app/Package.resolved, app/Package.swift, haptics/Package.resolved, keyboard/Package.resolved, status-bar/Package.resolved
Update the `Package.resolved` file to use latest version of `capacitor6-spm-test`, as the one cached had a problem with the framework urls.
Also fix the app package as it didn't have the tests path configured properly.
=> chore(ios): fix verify script

screen-reader/README.md
The example code snippet in docs for @capacitor/screen-reader does not compile. Use the `stateChange` event in example code rather than non-existent `screenReaderStateChange` event.
=> docs(screen-reader): Use stateChange event in example code

google-maps/README.md, google-maps/src/definitions.ts
mapId, androidMapId and iOSMapId are going to be available on next google-maps release (5.4.0), so adjust the `@since` for them.
=> docs(google-maps): adjust since for mapId properties

camera/src/web.ts
This PR adds promise rejections for the pwa camera plugin upon cancelation of the input element.
Previously, in the web implementation of the PWA camera plugin, the promise would remain unresolved if the user cancelled the input, as it was solely reliant on the 'change' event. This behaviour differed from the iOS/Android implementation, where the promise is rejected under similar circumstances.
closes https://github.com/ionic-team/capacitor-plugins/issues/1050
=> fix(camera): reject promise on web input cancel event

camera/README.md
The text is a slightly reworded version of https://developer.android.com/training/data-storage/shared/photopicker#device-availability
Removes the "android 19" part since is not relevant to us, and adds information about the `Intent.ACTION_OPEN_DOCUMENT` fallback as I think it's important for our users and it's not mentioned in the official docs, but it was mentioned in some blogs.
In my testing I've seen devices that got the backported photo picker even if I didn't add that xml, but better stick to the official docs as that might be a bug and might change in the future.
=> docs(camera): Information about Photo Picker fallback

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
On iOS and web we use `"User cancelled photos app"` message for both camera and gallery cancellation, on Android we were using a different message for gallery cancellation.
Unify the messages so they are the same in all platforms.
Use a constant for all reject calls.
Remove an unused import.
=> refactor(android)!: Unify gallery cancel message

camera/CHANGELOG.md, filesystem/CHANGELOG.md, google-maps/CHANGELOG.md, keyboard/CHANGELOG.md, screen-reader/CHANGELOG.md
cherry pick latest release of
- @capacitor/camera@5.0.8
- @capacitor/filesystem@5.2.0
- @capacitor/google-maps@5.4.0
- @capacitor/keyboard@5.0.7
- @capacitor/screen-reader@5.0.7
=> chore(release): publish [skip ci]

browser/android/src/main/AndroidManifest.xml, browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserControllerActivity.java, browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserControllerListener.java, browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
Closes #151 
This PR adds the `close()` method to the Android Browser Plugin.
We create an "intermediate" controller activity that launches the custom tabs, and when we want to close, we launch the same activity with `FLAG_ACTIVITY_CLEAR_TOP` which triggers `onNewIntent` where we can detect to destroy the activity & custom tabs, without sacrificing the existing activity stack.
=> feat(browser): implement close() method for android

package.json
Capacitor 6 and plugins are going to be published as latest, not latest-6
=> chore: Publish as latest

device/README.md, filesystem/README.md, preferences/README.md
This PR adds the [Apple Privacy Manifest Requirements](https://ionic.zendesk.com/hc/en-us/articles/22242418163735-Privacy-Manifest-Requirements) to the relevant plugins.
Addresses #2060
=> docs: add apple privacy manifest code requirements

scripts/publish-android.sh
This needs to be updated before publishing to native so main publishes a dependency on v6
=> chore: updated publishing version dependency for capacitor 6

app-launcher/README.md, app/README.md, browser/README.md, camera/README.md, clipboard/README.md, device/README.md, dialog/README.md, filesystem/README.md, geolocation/README.md, haptics/README.md, keyboard/README.md, local-notifications/README.md, motion/README.md, network/README.md, preferences/README.md, push-notifications/README.md, screen-orientation/README.md, screen-reader/README.md, share/README.md, splash-screen/README.md, status-bar/README.md, text-zoom/README.md, toast/README.md
For Capacitor 5 plugins use `latest-5` tag, except for google-maps as it doesn't have `latest-5` tag yet
=> chore: Update install instructions with latest-5 tag

screen-orientation/ios/Plugin/ScreenOrientation.swift
=> bug(@capacitor/screen-orientation): iOS landscape lock using incorrect mappings

camera/ios/Plugin/CameraExtensions.swift
Closes #2046
This fixes the issue for `5.x`.
The bug was due to an out-of-memory issue. The `self.draw` call kept the image in memory after usage. When transforming the image to a jpeg data, there wasn't enough memory available to perform the operation, so a `nil` data object was being returned, resulting in an empty image. 
Using `UIGraphicsImageContext` fixes the issue.
=> fix(ios): iOS panorama photos selected through CameraPlugin are corrupted

camera/ios/Sources/CameraPlugin/CameraPlugin.swift
If the image object can't be loaded, load its data representation. 
Considering that the code was duplicated for multiple and single selections, refactor the code to remove redundancy. 
For multiple selection, since it's impossible to cancel image loading when one fails, the refactor also changes concurrent loading to serial.
References: https://outsystemsrd.atlassian.net/browse/RMET-3243
=> fix(ios): Picking ProRAW pictures from Gallery

keyboard/ios/Plugin/Keyboard.m
(`5.x` cherry-pick).
Avoids breaking apps that use Apple CarPlay.
References: https://outsystemsrd.atlassian.net/browse/RMET-3229
=> fix(ios): apply filter to fetch correct scene object

action-sheet/README.md, google-maps/README.md
the install instructions weren't updated for google maps and action-sheet plugins, so they have not been published because there were no changes.
=> docs: Add missing latest-5 tag on install

action-sheet/package.json, app-launcher/package.json, app/package.json, browser/package.json, camera/package.json, clipboard/package.json, device/package.json, dialog/package.json, filesystem/package.json, geolocation/package.json, haptics/package.json, keyboard/package.json, local-notifications/package.json, motion/package.json, network/package.json, preferences/package.json, push-notifications/package.json, screen-orientation/package.json, screen-reader/package.json, share/package.json, splash-screen/package.json, status-bar/package.json, text-zoom/package.json, toast/package.json
preparation for Capacitor 7, the version has to be manually bumped
=> chore: bump version to 7.0.0-alpha.0

browser/ios/Sources/BrowserPlugin/BrowserPlugin.swift
Fixes a bug on @capacitor/browser on iOS: when trying to lock the device's orientation after the safari view controller was dismissed/closed by the user , an error occured: `None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeLeft`
This seemed to be happening because the view controller wasn't being properly closed/dismissed and the listeners were being incorrectly notified.
initial bug @ [here](https://github.com/ionic-team/capacitor-plugins/issues/2100)
reference: https://outsystemsrd.atlassian.net/browse/RMET-3453
=> fix(browser): call notifyListeners only when browser is dismissed

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Fixes a bug on @capacitor/camera on Android, where when taking a photo with `saveToGallery = true`, the camera only opened on the second attempt because of the permission to save to the gallery not being given.
This only happened for Android >= 10, and for those versions, we don't even need to request for permission to save to the gallery. More info [here](https://developer.android.com/media/camera/camera-deprecated/photobasics#TaskPath).
Closes #2210 
References: https://outsystemsrd.atlassian.net/browse/RMET-3767
=> feat(camera): only request permission to save to the gallery for Android <= 9

geolocation/ios/Sources/GeolocationPlugin/GeolocationPlugin.swift
- Replace iOS 14 deprecated calls.
- Move the `checkPermissions` verification within `locationManagerDidChangeAuthorization` to another queue to avoid the UI unresponsiveness warning thrown on runtime.
References: https://outsystemsrd.atlassian.net/browse/RMET-3808
=> RMET-3808 ::: Geolocation ::: iOS ::: Remove iOS 14 Deprecated Code

status-bar/README.md, status-bar/ios/Sources/StatusBarPlugin/CAPBridgeViewController.swift, status-bar/ios/Sources/StatusBarPlugin/StatusBar.swift, status-bar/ios/Sources/StatusBarPlugin/StatusBarPlugin.swift, status-bar/ios/Sources/StatusBarPlugin/UIColor.swift, status-bar/src/definitions.ts
Added information about the overlay property works on applications targeting Android 15.
=> docs(statusbar): Overlays webview property on Android 15

text-zoom/src/ios.ts
Plugins object is being removed in Capacitor 7
`getPreferred()` method is not really called, as there is a `getPreferred()` native iOS method, the Capacitor internal code will use the native method when available instead of the one in the typescript code. But needs to be declared since it implements `TextZoomPlugin` and typescript will complain if not present, so change it to just "throw".
=> refactor(text-zoom): don't use deprecated Plugins object

device/README.md, device/android/src/main/java/com/capacitorjs/plugins/device/Device.java, device/android/src/main/java/com/capacitorjs/plugins/device/DevicePlugin.java, device/ios/Sources/DevicePlugin/Device.swift, device/ios/Sources/DevicePlugin/DevicePlugin.swift, device/src/__tests__/useragent.spec.ts, device/src/definitions.ts
Remove the disk (total/available) size information from Device plugin as it's sensitive on iOS and requires a privacy manifest
closes https://github.com/ionic-team/capacitor-plugins/issues/2071
=> feat(device)!: remove disk size related information

haptics/android/src/main/java/com/capacitorjs/plugins/haptics/Haptics.java, haptics/src/definitions.ts
Removed some Android code that was causing warning on Android Studio and also deprecated types
=> refactor(haptics)!: remove unused and deprecated code

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraBottomSheetDialogFragment.java
- Fixes the `CameraSheetDialogFragment` that wasn't fully showing when orientation was landscape, by explicitly setting its state to `BottomSheetBehavior.STATE_EXPANDED`.
- Also removes unnecessary null check since `instanceof` will return `false` if `behavior` is null.
Closes: https://github.com/ionic-team/capacitor-plugins/issues/2224
=> fix(camera): Android dialog not fully showing when in landscape

browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java
- when trying to open blob urls, an app using the @capacitor/browser plugin would just crash, with an `ActivityNotFoundException`
- the try/catch block wasn't placed properly
references: https://outsystemsrd.atlassian.net/browse/RMET-3912
=> fix(android): crash when trying to open blob urls

filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/Filesystem.java, filesystem/android/src/main/java/com/capacitorjs/plugins/filesystem/FilesystemPlugin.java
Closes #6861
This PR runs `downloadFile` in an async task so it does not block other plugin calls.
=> fix(android): run downloadFile asynchronously

action-sheet/package.json, app-launcher/package.json, app/package.json, browser/package.json, camera/package.json, clipboard/package.json, device/package.json, dialog/package.json, filesystem/package.json, geolocation/package.json, haptics/package.json, keyboard/package.json, local-notifications/package.json, motion/package.json, network/package.json, preferences/package.json, push-notifications/package.json, screen-orientation/package.json, screen-reader/package.json, share/package.json, splash-screen/package.json, status-bar/package.json, text-zoom/package.json, toast/package.json
Change the peer dependencies from `next` to `>=7.0.0-rc.0`.
We still will need to change it to just `>=7.0.0` before the final release instead of doing `^7.0.0` as we do other years, to be more permissive about plugins that are not updated right away as we rarely do breaking changes in `@capacitor/core`.
=> chore: Use more permissive peerDependency

action-sheet/Package.swift, app-launcher/Package.swift, app/Package.swift, browser/Package.swift, camera/Package.swift, clipboard/Package.swift, device/Package.swift, dialog/Package.swift, filesystem/Package.swift, geolocation/Package.swift, haptics/Package.swift, keyboard/Package.swift, local-notifications/Package.swift, network/Package.swift, preferences/Package.swift, push-notifications/Package.swift, screen-orientation/Package.swift, screen-reader/Package.swift, share/Package.swift, splash-screen/Package.swift, status-bar/Package.swift, text-zoom/Package.swift, toast/Package.swift
Configure plugins `Package.swift` to use version 7.0.0 instead of main branch as main branch could have 6.x versions some times.
=> chore: make SPM use version 7 instead of main

README.md, filesystem/CHANGELOG.md, filesystem/README.md, geolocation/CHANGELOG.md, geolocation/README.md, nx.json, package.json
Inform of `@capacitor/filesystem` migration to new GitHub repository - To me merged when a future version of the filesystem plugin is released
Also includes updates for a few other capacitor plugins that are housed in separate repositories.
=> docs(filesystem): Plugin migration

splash-screen/android/src/main/java/com/capacitorjs/plugins/splashscreen/SplashScreen.java
clear the `onExitAnimationListener` once the animation ends, otherwise it will continue to get called on app resume, preventing changes on the UI such as status bar style changes since the `exitAnimationListener` "freezes" the UI before the animation and changes done while it's "frozen" won't take any effect.
=> fix(splash-screen): call clearOnExitAnimationListener on animation end

.github/workflows/publish-android.yml, .github/workflows/publish-latest.yml, scripts/android/publish-root.gradle, scripts/publish-android.sh
We currently publish in Maven Central through OSSRH, however this needs to be changed due OSSRH being shutdown in after June 30th 2025.
Migration of `com.capacitor` namespace to Central Portal has already been done, this PR takes care of updating the publishing logic - which uses a new token that is now accessed in different github secrets.
Relevant References:
- https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
- https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central
=> chore(android): Publishing migration to Central Portal

keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java, keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/KeyboardPlugin.java
On android 15+ we need to take the gesture bar into account (as well as the three button nav)
Closes: https://github.com/kensodemann/issue-53807
Testing notes (screenshots on Jira ticket):
Pixel 9 (physical, gesture navigation) → ✅
Pixel 9 (physical, 3 button navigation) → ✅
Pixel 8 pro emulator → ✅
Pixel 4 (android 14, emulator) → ✅
Pixel 4 (android 13, emulator) → ✅
Pixel 7a (android 15, emulator) → ✅
=> fix(android): fixed issues on android 15+ white space above keyboard

camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java
Addresses https://github.com/ionic-team/capacitor-plugins/issues/2140 and https://github.com/ionic-team/capacitor-plugins/issues/2339 
Android 13+ no longer has storage permission requests, and a permission request for "photos" alias was being requested, but because this alias has no permissions, nothing would happen.
This PR fixes the logic to instead call `checkPermissions` in such a scenario.
=> fix(camera): requestPermissions on Android 13+

keyboard/package.json, local-notifications/package.json, push-notifications/package.json, splash-screen/package.json, status-bar/package.json
Install `@capacitor/cli` in status bar plugin since it has a configuration option that depends on it but wasn't installed.
Update it to 7.x for the rest of packages that had it installed.
=> chore(dev-deps): Update @capacitor/cli to 7.x

action-sheet/package.json, app-launcher/package.json, app/package.json, browser/package.json, camera/package.json, clipboard/package.json, device/package.json, dialog/package.json, haptics/package.json, keyboard/package.json, local-notifications/package.json, motion/package.json, network/package.json, preferences/package.json, push-notifications/package.json, screen-orientation/package.json, screen-reader/package.json, share/package.json, splash-screen/package.json, status-bar/package.json, text-zoom/package.json, toast/package.json
To start Cap 8 alpha support of plugins, major version must be manually updated.
=> chore: bump version to 8.0.0-alpha.0
